---
weight_dir: ..\checkpoints # path to folder where checkpoints should be stored
name_load: carla2cityscapes-360000 # carla2kitti-400000 or carla2cityscapes-360000 or carla2vistas-360000 or carla2gta-140000

common:
  unpin: false # disable pinning for the loader
  batch_size: 1
  num_loaders: 0
  log_interval: 1 # print losses every X iterations
  seed: 1

train:
  max_epochs: -1
  max_iterations: 1000000
  save_epochs: -1 # save every X epochs
  save_iterations: 10000 # save every X iterations
  name_save: pfd2cs
  shuffle_train: true
  val_interval: 10000 # run inference on validation set every X iterations
   
test:
  shuffle_test: false

real_dataset:
  name: Cityscapes
  filelist: ..\config\data\Inference\files.txt # file with path to image in each line.

fake_dataset: 
  name: CARLA
  train_filelist: ..\config\data\Inference\train.txt
  val_filelist: ..\config\data\Inference\val.txt
  test_filelist: ..\config\data\Inference\test.txt # see above
  sampling: 
    type: 'matching'
    matched_crop_path:
    crop_weight_path: 

generator:
  type: hr
  config:
    encoder_type: ENCODER
    stem_norm: group
    num_stages: 3
    other_norm: group
    gbuffer_norm: RAD
    gbuffer_encoder_norm: residual
    num_gbuffer_layers: 1
  optimizer:
    type: adam
    learning_rate: 0.0001
    adam_beta: 0.9
    adam_beta2: 0.999
    clip_gradient_norm: 1000
  scheduler:
    type: 'step'
    step: 100000
    gamma: 0.5
    
discriminator:
  type: ppde
  run_always: false
  config:
    norm: group
    num_layers: 3
    max_dim: 256
  optimizer:
    type: adam
    learning_rate: 0.0001 
    adam_beta: 0.9
    adam_beta2: 0.999
    clip_gradient_norm: 1000
  scheduler:
    type: 'step'
    step: 1000000
    gamma: 0.5
    
objectives:
  gan: ls
  perceptual:
    type: 'lpips_vgg'
    weight: 5
  reg:
    weight: 0.03
...
